services:
  quota-service:
    container_name: quota-service
    image: hyperf/hyperf:8.3-alpine-v3.19-swoole-slim
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - '9501:9501'
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - quota-db
      - quota-redis

  quota-db:
    container_name: quota-db
    image: mariadb:latest
    volumes:
      - ./.docker/quota-db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: secret-password

  quota-redis:
    container_name: quota-redis
    image: redis:latest
    ports:
      - '6379:6379'
